### ISSUE TITLE
(Questions) How is state updated when making a bid and why is an ack passed to sender() twice?

### ISSUE THREAD

**Issue by DrewEaster** [boldradius/akka-dddd-template#1]
Hope you don't mind me asking for some clarity on the code...
### How is state updated when making a bid?

I'm looking at the code for `BidProcessor` and I'm unable to understand the following code:

``` scala
      handleProcessedCommand(sender(),
        if (timestamp < state.endTime && timestamp >= state.startTime) {
          val currentPrice = getCurrentBid(state)
          if (bidPrice > currentPrice) {
            // Successful bid
            ProcessedCommand(
              Some(BidPlacedEvt(id, buyer, bidPrice, timestamp)),
              PlacedBidAck(id, buyer, bidPrice, timestamp),
              None
            )
          } else {
            //Unsuccessful bid
            ProcessedCommand(
              Some(BidRefusedEvt(id, buyer, bidPrice, timestamp)),
              RefusedBidAck(id, buyer, bidPrice, currentPrice),
              None
            )
          }
        } else if (timestamp > state.endTime) {
          // auction expired
          ProcessedCommand(None, AuctionEndedAck(id), None)
        } else {
          ProcessedCommand(None, AuctionNotYetStartedAck(id), None)
        }
      )
```

The implementation of `handleProcessedCommand()` never appears to call `updateState()`:

``` scala
   processedCommand.event.fold(sender() ! processedCommand.ack) { evt =>
      persist(evt.logDebug("+++++++++++++  evt = " + _.toString)) { persistedEvt =>
        readRegion ! Update(await = true)
        sendr ! processedCommand.ack
        processedCommand.newReceive.fold({})(context.become)
      }
    }
```

So I'm at a bit of a loss as to how the internal state is updated. Surely, given that the `BidProcessor` _does_ need access to current state (for the purposes of correctly implementing the `getCurrentBid` method), it doesn't seem right that, in handling a `BidPlacedEvt`, the internal state of the `BidProcessor` is not updated? I can see why `BidRefusedEvt` doesn't _have_ to be handled as there's no logic within `BidProcessor` (only in `BidView`) that relies on refused bids being tracked.

Am I missing something obvious here?
### Why is an ack passed to sender() twice?

Revisiting  `handleProcessedCommand()`:

``` scala
   processedCommand.event.fold(sender() ! processedCommand.ack) { evt =>
      persist(evt.logDebug("+++++++++++++  evt = " + _.toString)) { persistedEvt =>
        readRegion ! Update(await = true)
        sendr ! processedCommand.ack
        processedCommand.newReceive.fold({})(context.become)
      }
    }
```

I don't understand why the code calls `processedCommand.event.fold(sender() ! processedCommand.ack)` and then, post successful persistence, again calls `sendr ! processedCommand.ack`.

Why would the `sender()` be notified before it's known whether the event was persisted?

**Comment by dsugden** [comment]
Hi,

Don't mind at all, and you have highlighted an issue, thnx!
I changed this class to use the become pattern 4 days ago, missed the call
to update when bid is placed.

If I can get wifi at SFO , I'll fix and push, otherwise tomorrow.

Thanks !

**Comment by dsugden** [comment]
We aren't actually acking twice:

We fold on the option of event:
   processedCommand.event.fold

And ack in either case (None)( e => ...)

**Comment by DrewEaster** [comment]
Oh, of course. My bad :-)

I'll give myself 50% - right with point (1) and wrong with point (2).

**Comment by dsugden** [comment]
Hi Drew,

Fixed that. Thanks again for your catch, and interest. 
We are very interested in any other reactions/comments etc. you might have here!

-dave

**Comment by DrewEaster** [comment]
Thanks Dave. I'll make further comments if/when I come up with them.
