### ISSUE TITLE
Stopping one of backend nodes

### ISSUE THREAD

**Issue by sbuljat** [boldradius/akka-dddd-template#4]
Hi,

I'm using your template and I run into one issue using 1 frontend node and 2 backend nodes. Everything works fine until I stop backend node which is marked as a firstSeedNode. After that web service timeouts (AskTimeout), as if this actor is connected only to the first seed?
Shouldn't this automatically transfer request to the remaining backend node?

Best,
Stjepan

**Comment by sbuljat** [comment]
This is the exact exception:

Execution exception[[AskTimeoutException: Ask timed out on [Actor[akka://ClusterSystem/user/sharding/BidView#1714775487]] after [30000 ms]]]

**Comment by katrinsharp** [comment]
Hi sbuljat,

Per [Akka documentation](http://doc.akka.io/docs/akka/snapshot/scala/cluster-usage.html#Joining_to_Seed_Nodes):

"Once more than two seed nodes have been started it is no problem to shut down the first seed node. If the first seed node is restarted, it will first try to join the other seed nodes in the existing cluster."

You need to have at least two nodes, and then it will be fine to shutdown the first one.

**Comment by sbuljat** [comment]
Thanks!
